services:
  # MariaDB Database
  mariadb:
    image: mariadb:10.6
    container_name: erpnext-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
      - type: bind
        source: ${MARIADB_DIR}
        target: /var/lib/mysql/backup
    networks:
      - erpnext-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis-cache:
    image: redis:7-alpine
    container_name: erpnext-redis-cache
    restart: unless-stopped
    volumes:
      - redis-cache-data:/data
    networks:
      - erpnext-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Queue
  redis-queue:
    image: redis:7-alpine
    container_name: erpnext-redis-queue
    restart: unless-stopped
    volumes:
      - redis-queue-data:/data
    networks:
      - erpnext-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Socketio
  redis-socketio:
    image: redis:7-alpine
    container_name: erpnext-redis-socketio
    restart: unless-stopped
    volumes:
      - redis-socketio-data:/data
    networks:
      - erpnext-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ERPNext Backend
  backend:
    image: frappe/erpnext:v15
    container_name: erpnext-backend
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      REDIS_CACHE: ${REDIS_CACHE_HOST}:6379
      REDIS_QUEUE: ${REDIS_QUEUE_HOST}:6379
      REDIS_SOCKETIO: ${REDIS_SOCKETIO_HOST}:6379
    volumes:
      - type: bind
        source: ${SITES_DIR}
        target: /home/frappe/frappe-bench/sites
      - type: bind
        source: ${LOGS_DIR}
        target: /home/frappe/frappe-bench/logs
      - type: bind
        source: ${QONTO_CONNECTOR_DIR}
        target: /home/frappe/frappe-bench/apps/qonto_connector
    networks:
      - erpnext-network
    ports:
      - "${BACKEND_PORT}:8000"
    working_dir: /home/frappe/frappe-bench/sites
    command: >
      bash -c "
        cd /home/frappe/frappe-bench/sites;
        if [ ! -d ${SITE_NAME} ]; then
          echo 'Creating new site: ${SITE_NAME}';
          bench new-site ${SITE_NAME} --db-root-password ${DB_ROOT_PASSWORD} --admin-password ${ADMIN_PASSWORD} --no-mariadb-socket;
          bench --site ${SITE_NAME} install-app erpnext;
          echo 'Installing Qonto Connector app';
          cd /home/frappe/frappe-bench;
          bench get-app qonto_connector file:///home/frappe/frappe-bench/apps/qonto_connector;
          bench --site ${SITE_NAME} install-app qonto_connector;
          bench --site ${SITE_NAME} set-config developer_mode 1;
          bench --site ${SITE_NAME} clear-cache;
        fi;
        cd /home/frappe/frappe-bench;
        bench serve --port 8000
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8000 > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  # ERPNext Frontend (Nginx)
  frontend:
    image: frappe/erpnext:v15
    container_name: erpnext-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    environment:
      BACKEND: backend:8000
      SOCKETIO: socketio:9000
      SITE_NAME: ${SITE_NAME}
    volumes:
      - type: bind
        source: ${SITES_DIR}
        target: /home/frappe/frappe-bench/sites
    networks:
      - erpnext-network
    ports:
      - "${FRONTEND_PORT}:8080"
    working_dir: /home/frappe/frappe-bench
    command: ["nginx-entrypoint.sh"]

  # Socketio for real-time features
  socketio:
    image: frappe/erpnext:v15
    container_name: erpnext-socketio
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
      redis-socketio:
        condition: service_healthy
    environment:
      REDIS_SOCKETIO: redis-socketio:6379
    volumes:
      - type: bind
        source: ${SITES_DIR}
        target: /home/frappe/frappe-bench/sites
    networks:
      - erpnext-network
    ports:
      - "${SOCKETIO_PORT}:9000"
    working_dir: /home/frappe/frappe-bench
    command: ["node", "apps/frappe/socketio.js"]

  # Queue Workers
  queue-default:
    image: frappe/erpnext:v15
    container_name: erpnext-queue-default
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      REDIS_CACHE: ${REDIS_CACHE_HOST}:6379
      REDIS_QUEUE: ${REDIS_QUEUE_HOST}:6379
    volumes:
      - type: bind
        source: ${SITES_DIR}
        target: /home/frappe/frappe-bench/sites
      - type: bind
        source: ${QONTO_CONNECTOR_DIR}
        target: /home/frappe/frappe-bench/apps/qonto_connector
    networks:
      - erpnext-network
    working_dir: /home/frappe/frappe-bench
    command: ["bench", "worker", "--queue", "default"]

  queue-short:
    image: frappe/erpnext:v15
    container_name: erpnext-queue-short
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      REDIS_CACHE: ${REDIS_CACHE_HOST}:6379
      REDIS_QUEUE: ${REDIS_QUEUE_HOST}:6379
    volumes:
      - type: bind
        source: ${SITES_DIR}
        target: /home/frappe/frappe-bench/sites
      - type: bind
        source: ${QONTO_CONNECTOR_DIR}
        target: /home/frappe/frappe-bench/apps/qonto_connector
    networks:
      - erpnext-network
    working_dir: /home/frappe/frappe-bench
    command: ["bench", "worker", "--queue", "short"]

  queue-long:
    image: frappe/erpnext:v15
    container_name: erpnext-queue-long
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      REDIS_CACHE: ${REDIS_CACHE_HOST}:6379
      REDIS_QUEUE: ${REDIS_QUEUE_HOST}:6379
    volumes:
      - type: bind
        source: ${SITES_DIR}
        target: /home/frappe/frappe-bench/sites
      - type: bind
        source: ${QONTO_CONNECTOR_DIR}
        target: /home/frappe/frappe-bench/apps/qonto_connector
    networks:
      - erpnext-network
    working_dir: /home/frappe/frappe-bench
    command: ["bench", "worker", "--queue", "long"]

  # Scheduler
  scheduler:
    image: frappe/erpnext:v15
    container_name: erpnext-scheduler
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      redis-queue:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      REDIS_CACHE: ${REDIS_CACHE_HOST}:6379
      REDIS_QUEUE: ${REDIS_QUEUE_HOST}:6379
    volumes:
      - type: bind
        source: ${SITES_DIR}
        target: /home/frappe/frappe-bench/sites
      - type: bind
        source: ${QONTO_CONNECTOR_DIR}
        target: /home/frappe/frappe-bench/apps/qonto_connector
    networks:
      - erpnext-network
    working_dir: /home/frappe/frappe-bench
    command: ["bench", "schedule"]

networks:
  erpnext-network:
    driver: bridge

volumes:
  mariadb-data:
  redis-cache-data:
  redis-queue-data:
  redis-socketio-data:
